export const ACTION_TYPES = {
  FETCH_SHIPMENTS_REQUEST: 'shipmentScreen/FETCH_SHIPMENTS_REQUEST',
  FETCH_SHIPMENTS_SUCCESS: 'shipmentScreen/FETCH_SHIPMENTS_SUCCESS',
  SHIPMENTS_PAGE_ERROR: 'shipmentScreen/SHIPMENTS_PAGE_ERROR',
  SHIPMENTS_PAGE_LOADING: 'shipmentScreen/SHIPMENTS_PAGE_LOADING',
};
