export const ACTION_TYPES = {
    FETCH_SHIPMENT_REQUEST: 'shipmentDetailsScreen/FETCH_SHIPMENT_REQUEST',
    FETCH_SHIPMENT_SUCCESS: 'shipmentDetailsScreen/FETCH_SHIPMENT_SUCCESS',
    UPDATE_SHIPMENT_REQUEST: 'shipmentDetailsScreen/UPDATE_SHIPMENT_REQUEST',
    UPDATE_SHIPMENT_SUCCESS: 'shipmentDetailsScreen/UPDATE_SHIPMENT_SUCCESS',
    SHIPMENT_DETAILS_PAGE_ERROR: 'shipmentScreen/SHIPMENT_DETAILS_PAGE_ERROR',
    SHIPMENT_DETAILS_PAGE_LOADING: 'shipmentScreen/SHIPMENT_DETAILS_PAGE_LOADING',
};
